# /.github/release-drafter.yml
# Configuration for release-drafter
template: |
  ## ## ## {{ version }} ({{ date }})

  ### {{#each categories}}
  **{{ title }}**
  {{#each issues}}
    * {{#if linked}} (#{{ number }}) {{/if}} {{ title }} (@{{ author }})
  {{/each}}
  {{/each}}

exclude:
  labels: []  # Empty list for excluding labels
  authors: []  # Empty list for excluding authors

categories:
  - title: Nouvelles fonctionnalités 
    labels:
      - feat
  - title: Modifications de code ⚙️
    labels:
      - refactor
  - title: Mises à jour de style ✨
    labels:
      - style
  - title: Corrections de bugs 
    labels:
      - fix
  - title: Tests 
    labels:
      - test
  - title: Documentation 
    labels:
      - doc
