name: Generate Release Note

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Generate Release Note
        run: ./generate-release-note.sh
        
      - name: Commit Release Note
        run: |
          git config --local user.email "alternative.rvb@gmail"
          git config --local user.name "GitHub Action"
          git add RELEASE.md
          git commit -m "Add release note [skip ci]"
          git push
