name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Latest Commit Info
        id: latest_commit
        run: |
          echo "::set-output name=commit_hash::$(git log -1 --format='%H')" 
          echo "::set-output name=commit_message::$(git log -1 --format='%s')"

      - name: Get Previous Tag
        id: prev_tag
        run: |
          echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"

      - name: Generate Changelog Content
        id: generate_changelog
        run: |
          echo "::group::Generating Changelog"
          git log --pretty=format:"* %s (%cn)" ${{ steps.prev_tag.outputs.previous_tag }}..${{ github.ref }} > changelog.txt
          echo "::endgroup::"
          echo "::set-output name=changelog::$(cat changelog.txt)"  # Capture entire changelog content

      - name: Create Draft Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release Notes for ${{ github.ref }}"
          body: ${{ steps.generate_changelog.outputs.changelog }}  # Use captured changelog content
          draft: true
