# /.github/workflows/release.yml
name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ./release-drafter.yml
          version: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "::set-env name=RELEASE_VERSION::$(echo ${{ github.ref }})"
          echo "::set-env name=RELEASE_DATE::$(date +%Y-%m-%d)"
          # Add logic to generate changelog content and write to a file
          # echo "::set-env name=RELEASE_CHANGELOG::$(cat changelog.txt)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Version: ${{ env.RELEASE_VERSION }}
            Date: ${{ env.RELEASE_DATE }}
            Changelog:
            ${{ env.RELEASE_CHANGELOG }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token as an environment variable
        
