name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Generate Changelog Content
        id: generate_changelog
        run: |
          echo "::group::Generating Changelog"
          CHANGELOG=$(git log $(git describe --tags --abbrev=0 HEAD~1)..HEAD --pretty=format:"* %s (%cn)")
          echo "$CHANGELOG"
          echo "::endgroup::"
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Create Draft Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}  # Optional, can be customized
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: true  # Set to true for draft release
