name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install --path vendor/bundle

      - name: Generate Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec release-drafter
