name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Previous Tag
        id: prev_tag
        run: |
          echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"

      - name: Generate Changelog Content Debug
        id: generate_changelog
        run: |
          echo "::group::Generating Changelog"
          git log --pretty=format:"* %s (%cn)" ${{ steps.prev_tag.outputs.previous_tag }}..${{ github.ref }} > changelog.txt
          cat changelog.txt
          echo "::endgroup::"
          echo "::set-output name=changelog_file::changelog.txt"

      - name: Read Changelog Content
        id: read_changelog
        run: |
          changelog_content=$(cat ${{ steps.generate_changelog.outputs.changelog_file }})
          echo "::set-output name=changelog_content::$changelog_content"

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          files: |
            ${{ steps.generate_changelog.outputs.changelog_file }}
          tag_name: ${{ github.ref }}
          name: "Release Notes for ${{ github.ref }}"
          body: ${{ steps.read_changelog.outputs.changelog_content }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
