name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - '*'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Récupère tout l'historique du dépôt pour obtenir tous les commits

      - name: Generate Changelog Content
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Create Draft Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            $(cat CHANGELOG.md)
          draft: true
