# /.github/workflows/release.yml

name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - '*'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Récupère tout l'historique du dépôt pour obtenir tous les commits

      - name: Get Commit Info
        id: commit_info
        run: |
          echo "::group::Getting Commit Info"
          echo "::set-output name=commit_message::$(git log --pretty=format:"%s (%cn)")"
          echo "::set-output name=commit_hash::$(git log --pretty=format:"%H")"
          echo "::endgroup::"

      - name: Generate Changelog Content
        id: generate_changelog
        run: |
          echo "::group::Generating Changelog"
          echo "${{ steps.commit_info.outputs.commit_message }}"
          echo "::endgroup::"
          echo "::set-output name=changelog::${{ steps.commit_info.outputs.commit_message }}"

      - name: Create Draft Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release Notes for ${{ github.ref }}"
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: true
