name: Generate Release Notes and Create Draft Release

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Récupère tout l'historique du dépôt pour obtenir tous les commits

      - name: Generate Changelog Content
        id: generate_changelog
        run: |
          echo "::group::Generating Changelog"
          CHANGELOG=$(git log --pretty=format:"* %s (%cn)")
          echo "$CHANGELOG"
          echo "::endgroup::"
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Create Draft Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Remplacez avec la balise de version appropriée
          release_name: Version 1.0.0  # Remplacez avec le nom de version approprié
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: true  # Set to true for draft release
