# /.github/workflows/release.yml
name: Generate Release Notes and Create Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ./release-drafter.yml
          version: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Notes
        id: release_notes
        env:
          RELEASE_VERSION: ${{ github.ref }}
          RELEASE_DATE: $(date +%Y-%m-%d)
        run: |
          # Replace this with your logic to generate changelog content
          # This example assumes commits are properly formatted
          RELEASE_CHANGELOG=$(git log --since="$(git describe --tags --abbrev=0 HEAD~1)" --pretty=format:"* %s (%cn)")
          echo "::set-output name=changelog::$RELEASE_CHANGELOG"
        shell: bash
  
        
        
      
